:concurrency: 25
development:
  :pidfile: tmp/pids/sidekiq-cron.pid


production:
  :pidfile: ../../shared/tmp/pids/sidekiq-cron.pid
  :logfile: ../../shared/log/sidekiq-cron.log
  :concurrency: 25

:queues:
  - process_feed
  - process_feed_entry
  - cron

